# Generated by Django 4.2 on 2023-04-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pictures', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1000)),
                ('MuscleGroups', models.CharField(max_length=50)),
                ('NumberOfRepetitions', models.IntegerField()),
                ('ExerciseTime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinkVideo', models.CharField(max_length=50)),
                ('TimeMovies', models.CharField(max_length=50)),
                ('Inventory', models.CharField(max_length=50)),
                ('StudyArea', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Datebirth', models.DateField()),
                ('Sex', models.BooleanField()),
                ('Height', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.IntegerField()),
                ('Breast', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Waist', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Hips', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.user')),
            ],
        ),
    ]
